### ISSUE TITLE
Rename to ClimaBiogeochemistry.jl?

### ISSUE THREAD

**Issue by glwagner** [CliMA/ClimaOceanBiogeochemistry.jl#1]
@seamanticscience I think the safe path is to rename this to ClimaBiogeochemistry.jl.

What do you think?

**Comment by seamanticscience** [comment]
It was a fun name, but that makes sense...

Does it need to be more specific, like include "Ocean" in the name?

**Comment by glwagner** [comment]
Hmm that's a good point

**Comment by glwagner** [comment]
how about “Aqueous.jl”

**Comment by glwagner** [comment]
another vote for "Biogeochemiggles"

**Comment by glwagner** [comment]
another vote for "ClimaOceanBiogeochemistry" or "ClimaOceanBGC"

**Comment by emilyzakem** [comment]
I really really like ClimaOceanBiogeochemiggles. But ClimaOceanBiogeochemistry is so self-explanatory.
