### ISSUE TITLE
Implement a few non-trivial tests

### ISSUE THREAD

**Issue by glwagner** [CliMA/ClimaOceanBiogeochemistry.jl#13]
Currently we've only got

https://github.com/CliMA/ClimaOceanBiogeochemistry.jl/blob/0092903ef7df27465a4c3965c07fc6173c7e1217/test/runtests.jl#L3

which is of limited utility.

We have a bit of source code so we can add tests for that. #12 also adds some non-trivial docs.

**Comment by seamanticscience** [comment]
I added some type and reference coefficient tests for the carbon system in #11.

**Comment by seamanticscience** [comment]
...and now the testing of `CarbonAlkalinityNutrients` simulation runs successfully too (also in #11).

>      Testing Running tests...
>      Test Summary: | Pass  Total  Time
>      CarbonSolvers |   24     24  7.6s
>      Test Summary:                     | Pass  Total  Time
>      NutrientsPlanktonBacteriaDetritus |    1      1  0.0s
>      [ Info: Initializing simulation...
>      [ Info:     ... simulation initialization complete (159.115 ms)
>      [ Info: Executing initial time step...
>      [ Info:     ... initial time step complete (32.222 seconds).
>      [ Info: Simulation is stopping after running for 32.637 seconds.
>      [ Info: Model iteration 3 equals or exceeds stop iteration 3.
>      Test Summary:             | Pass  Total     Time
>      CarbonAlkalinityNutrients |    3      3  1m18.3s
>           Testing ClimaOceanBiogeochemistry tests passed

**Comment by navidcy** [comment]
there exist some non-trivial tests atm; should we close this?

**Comment by seamanticscience** [comment]
@hengdiliang @emilyzakem would it be useful to add some checks associated with `nutrients_plankton_bacteria_detritus.jl`?

**Comment by glwagner** [comment]
happy to close this
