### ISSUE TITLE
Should we include more examples in the docs?

### ISSUE THREAD

**Issue by glwagner** [CliMA/ClimaOceanBiogeochemistry.jl#25]
We have four examples:

https://github.com/CliMA/ClimaOceanBiogeochemistry.jl/tree/main/examples

But only one is actually built into the docs:

https://github.com/CliMA/ClimaOceanBiogeochemistry.jl/blob/67d28b8e79b3a1df1fbe94d494a3024304178a80/docs/make.jl#L16-L18

**Comment by navidcy** [comment]
All of them?

**Comment by glwagner** [comment]
If they can be afforded
